version: "3"
services:
  example:
    container_name: example_local
    build:
      context: ./example/target/docker
      dockerfile: Dockerfile
    tty: true
    network_mode: host
    env_file:
      - ./example/local.env
    depends_on:
      - postgres
  postgres:
    container_name: postgres_local
    image: postgres:13
    network_mode: host
    env_file:
      - ./example/local.env
