version: "3"
services:
  tracker:
    container_name: tracker_local
    build:
      context: ./example/tracker/target/docker
      dockerfile: Dockerfile
    tty: true
    network_mode: host
    env_file:
      - ./example/tracker/local.env
    depends_on:
      - postgres
  postgres:
    container_name: postgres_local
    image: postgres:13
    network_mode: host
    env_file:
      - ./example/tracker/local.env
